### ISSUE TITLE
How to Comment?

### ISSUE THREAD

**Issue by jimrothstein** [jonthegeek/wapir#54]
Appropriate method to comment on book's :
- outline
- text
- code

How/where to make 
-  **minor** comment,
-  **major** comment

**Comment by jonthegeek** [comment]
The book itself is extremely in-flux right now. For most things, I think R4DS Slack or maybe r4ds.io/wapir is the best place to comment, since I plan to use that book club to elicit feedback.

I'll try to update the various [CONTRIBUTING.md](https://github.com/jonthegeek/wapir/blob/main/.github/CONTRIBUTING.md) files before TOO long to lay that info out in more detail (and I'll keep this issue open until I do that).
